apiVersion: v2
name: order-service
description: Order Service Helm chart for E-Commerce Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - microservices
  - order
maintainers:
  - name: DevOps Team
