apiVersion: v2
name: product-service
description: Product Service Helm chart for E-Commerce Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ecommerce
  - microservices
  - product
maintainers:
  - name: DevOps Team
